services:
  grafana:
    image: grafana/grafana:latest
    container_name: mlb-grafana
    ports:
      - "3000:3000"

  jobmanager:
    build:
        context: ./calculation
        dockerfile: Dockerfile
    container_name: mlb-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build:
        context: ./calculation
        dockerfile: Dockerfile
    container_name: mlb-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  #sql-client:
  #  image: flink:latest
  #  depends_on:
  #    - jobmanager
  #  command: bin/sql-client.sh
  #  environment:
  #      - |
  #        FLINK_PROPERTIES=
  #        jobmanager.rpc.address: jobmanager
  #        rest.address: jobmanager

  kafka:
    image: apache/kafka:latest
    container_name: mlb-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: mlb-kafka
    volumes:
        - kafka_data:/var/lib/kafka/data

  #kafka-ui:
  #  image: provectuslabs/kafka-ui:latest
  #  container_name: mlb-kafka-ui
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - kafka
  #  environment:
  #    KAFKA_CLUSTERS_0_NAME: mlb-kafka
  #    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  postgres:
    image: postgres:17
    container_name: mlb-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #ingest:
  #  build: ./ingest
  #  container_name: mlb-ingest
  #  depends_on:
  #    - postgres
  #  environment:
  #    - POSTGRES_DB_CONNECT_STRING="postgresql+psycopg://postgres:mysecretpassword@localhost:5432/postgres"
volumes:
    postgres_data:
    kafka_data: