services:
  grafana:
    image: grafana/grafana:latest
    container_name: mlb-grafana
    ports:
      - "3000:3000"

  flink:
    image: flink:latest
    container_name: mlb-flink
    ports:
      - "8081:8081"

  kafka:
    image: apache/kafka:latest
    container_name: mlb-kafka
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: mlb-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  postgres-raw:
    image: postgres:17
    container_name: mlb-postgres-raw
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-analytics:
    image: postgres:17
    container_name: mlb-postgres-analytics
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: