apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432

    user: grafana

    secureJsonData:
      password: grafana

    jsonData:
      database: postgres
      sslmode: disable

    isDefault: true