from postgres:latest

# CREATE USER grafanareader WITH PASSWORD 'password';
  #GRANT USAGE ON SCHEMA public TO grafanareader;
  #GRANT SELECT ON public.game_state TO grafanareader;
  #GRANT SELECT ON public.innings TO grafanareader;
  #GRANT SELECT ON public.pitchers TO grafanareader;